name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
    
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          IGNORED_REPOS: "KaelSM"
          TIME_RANGE: last_7_days
          # TIME_RANGE: last_30_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
